version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_URL=http://backend:8000
    image: felixivance/moringa-yolomy-client:v1.0.0
    networks:
      - moringa-yolomy-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy
    image: felixivance/moringa-yolomy-backend:v1.0.0
    networks:
      - moringa-yolomy-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - moringa-yolomy-network

volumes:
  mongodbdata:

networks:
  moringa-yolomy-network:
    driver: bridge
