version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - moringa-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - moringa-network

networks:
  moringa-network:
    driver: bridge

volumes:
  mongodbdata:
