---
# tasks file for setup-backend
- name: Build and run backend container
  docker_container:
    name: backend
    image: "{{ docker_backend_image }}"
    state: started
    restart_policy: always
    ports:
      "8000:8000"
    env:
      MONGODB_URI: " {{ mongodb_uri }}"
    links:
      - mongo