apiVersion: apps/v1
kind: Deployment # Kind of resource
metadata:
  name: client # Name of the deployment
spec:
  replicas: 2 # Number of pods to run
  selector: # Label selector
    matchLabels: # Match labels
      app: client # Label to match
  template: # Pod template this means: create a pod with the following specifications
    metadata: # Metadata this means: give the pod a name
      labels:
        app: client # Label to apply 
    spec: # Pod specifications means: create a pod with the following specifications
      containers: # Containers this means: run the following containers
      - name: client # Name of the container
        image: felixivance/moringa-yolomy-client:v1.0.0 # Image to use means: use the following image
        resources: # Resources this means: set the resource limits
          limits: # Limits this means: set the maximum resource limits
            memory: "128Mi" # Memory this means: set the maximum memory limit in this case 128Mi (128 Megabytes)
            cpu: "500m" # CPU this means: set the maximum CPU limit in this case 500m (500 milliCPU)
        ports:
        - containerPort: 3000
      env:
        - name: REACT_APP_URL
          value: http://backend:8000
