apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend # Label to select means: select pods with the label app: backend
  ports:
    - protocol: TCP # Protocol to use means: use the TCP protocol ie Transmission Control Protocol
      port: 8000
      targetPort: 8000
