- hosts: all
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - test-connectivity
    - update-server
    - setup-docker
    - clone-repository
    - update-directory-ownership
    - run-docker-compose
    # - setup-mongo-db
    # - setup-backend
    # - setup-front-end